[project]
name = "tlkr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.uv.workspace]
members = [
    "tlkr-server",
    "tlkr-core",
    "tlkr-cli",
]
